name: Build Docker image for OMA manuscript
'on':
  push:
    branches:
    - devel
env:
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
jobs:
  rworkflows:
    permissions: write-all
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})
    container: ${{ matrix.config.cont }}
    strategy:
      fail-fast: ${{ false }}
      matrix:
        config:
        - os: ubuntu-latest
          bioc: '3.22'
          r: '4.5.2'
          cont: ghcr.io/bioconductor/bioconductor_docker:devel
          rspm: ~
          python-version: '3.14'
    steps:
    - uses: neurogenomics/rworkflows@master
      with:
        run_bioccheck: no
        run_rcmdcheck: no
        as_cran: yes
        run_vignettes: no
        has_testthat: no
        run_covr: no
        run_pkgdown: no
        has_runit: no
        has_latex: no
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run_docker: yes
        runner_os: ${{ runner.os }}
        cache_version: cache-v1
        docker_registry: ghcr.io
        force_install: no
        run_telemetry: yes
        free_diskspace: no
        miniforge_variant: ''
        environment_file: https://github.com/qiime2/distributions/blob/dev/2026.4/qiime2/released/rachis-qiime2-linux-64-conda.yml
